# permissions for end users to edit kubestatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubestatus-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubestatus-editor-role
rules:
- apiGroups:
  - crd.soubai.me
  resources:
  - kubestatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.soubai.me
  resources:
  - kubestatuses/status
  verbs:
  - get
